version: 1
disable_existing_loggers: true

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  root:
    format: '%(name)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

  console_root:
    class: logging.StreamHandler
    level: WARNING 
    formatter: root
    stream: ext://sys.stdout

loggers:
  baslerpi:
    level: WARNING
    propage: yes
  baslerpi.io.cameras.cameras:
    handlers: [console]
    level: DEBUG
    propagate: no
  baslerpi.web_utils:
    handlers: [console]
    propagate: no
  baslerpi.processing.annotate:
    handlers: [console]
    propagate: no
  baslerpi.scripts.run:
    handlers: [console]
    level: DEBUG


root:
  level: ERROR
  handlers: [console_root]
